const {test}=require('node:test');const assert=require('node:assert/strict');const {Repository,LocalStorageAdapter,migrateLegacyData,authenticate}=require('../public/v2/domain');
const legacy={anak:[{id:'a',nama:'A',saldo:2000,tugas:[{id:'m',nama:'Belajar',poin:10}],harian:{}},{id:'b',nama:'B',saldo:0,tugas:[],harian:{}}],hadiah:[{id:'r',nama:'Es krim'}],riwayat:[]};
function setup(){const map=new Map();const storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};const r=new Repository(new LocalStorageAdapter(storage));r.init(legacy);return r}
function reward(r,patch){r.parent=true;r.save('rewards',{...r.state.rewards[0],...patch});r.parent=false}
test('migration preserves balances, legacy object and existing storage',()=>{const r=setup();assert.equal(r.state.children[0].points,2000);assert.deepEqual(r.state.legacy,legacy);assert.equal(legacy.anak[0].saldo,2000);assert.equal(r.state.dataVersion,3);assert.equal(r.state.schemaVersion,3);assert.ok(r.state.children[0].avatarFallback);assert.ok(r.state.children[0].themeColor);assert.ok(Array.isArray(r.state.dailyRecords));assert.ok(Array.isArray(r.state.settings.penaltyPresets))});
test('mission adds points and XP once per period',()=>{const r=setup();r.complete('a',r.state.missions[0].id);assert.equal(r.state.children[0].points,2010);assert.equal(r.state.children[0].xp,10);assert.throws(()=>r.complete('a',r.state.missions[0].id));assert.equal(r.state.children[1].points,0)});
test('approval awards only once; rejection awards nothing',()=>{const r=setup();r.parent=true;r.save('missions',{...r.state.missions[0],requiresApproval:true});const c=r.complete('a',r.state.missions[0].id);assert.equal(r.state.children[0].points,2000);r.approveMission(c.id,true);assert.equal(r.state.children[0].points,2010);assert.throws(()=>r.approveMission(c.id,true))});
test('gacha consumes points and idempotent request creates one result',()=>{const r=setup();const a=r.performGacha('a','key');assert.equal(r.state.children[0].points,1000);assert.equal(r.performGacha('a','key').id,a.id);assert.equal(r.state.gachaResults.length,1)});
test('insufficient points cannot be replaced with money',()=>{const r=setup();r.parent=true;r.addIncome('b',1000000,'spending','gift','Gift');assert.throws(()=>r.performGacha('b','key'));assert.equal(r.total('b'),1000000)});
test('zero stock excluded and empty pool leaves points unchanged',()=>{const r=setup();reward(r,{stock:0});assert.equal(r.getEligibleRewards().length,0);assert.throws(()=>r.performGacha('a','key'));assert.equal(r.state.children[0].points,2000)});
test('finite stock decrements',()=>{const r=setup();reward(r,{stock:1});r.performGacha('a','key');assert.equal(r.state.rewards[0].stock,0)});
test('weighted selection boundaries',()=>{const r=setup(),pool=[{weight:1,id:1},{weight:3,id:2}];assert.equal(r.calculateWeightedReward(pool,()=>0).id,1);assert.equal(r.calculateWeightedReward(pool,()=>.99).id,2)});
test('wallet prevents negatives and transfer conserves total',()=>{const r=setup();r.parent=true;r.addIncome('a',100,'spending','gift','Gift');r.transferBetweenBuckets('a','spending','saving',40);assert.equal(r.total('a'),100);assert.equal(r.wallet(r.state,'a').saving,40);assert.throws(()=>r.expense('a','spending',61,'Snack'));assert.equal(r.total('a'),100)});
test('allocation exact amount and idempotent consumption',()=>{const r=setup();r.parent=true;r.addIncome('a',100,'allocate','gift','Gift');const id=r.state.incomes[0].id;assert.throws(()=>r.allocateIncome(id,{spending:50,saving:0,goal:0,sharing:0}));r.allocateIncome(id,{spending:50,saving:40,goal:0,sharing:10});assert.equal(r.total('a'),100);assert.throws(()=>r.allocateIncome(id,{spending:50,saving:40,goal:0,sharing:10}))});
for(const b of ['saving','sharing'])test(b+' reward auto credited once',()=>{const r=setup();reward(r,{type:b,value:20000});const result=r.performGacha('a','key');assert.equal(r.wallet(r.state,'a')[b],20000);assert.throws(()=>r.redeemGachaResult(result.id,b));assert.equal(r.total('a'),20000)});
test('convertible reward selected bucket once',()=>{const r=setup();reward(r,{convertible:true,conversionValue:20000});const result=r.performGacha('a','key');r.redeemGachaResult(result.id,'saving');assert.equal(r.wallet(r.state,'a').saving,20000);assert.throws(()=>r.redeemGachaResult(result.id,'sharing'))});
test('goal completion and spend approval',()=>{const r=setup();r.parent=true;r.save('goals',{childId:'a',name:'Buku',targetAmount:100});const gid=r.state.goals[0].id;r.addIncome('a',100,'spending','gift','Gift');r.transferBetweenBuckets('a','spending','goal',100,gid);assert.equal(r.state.goals[0].status,'completed');r.parent=false;r.useGoal(gid);assert.equal(r.total('a'),100);r.parent=true;r.approveWallet(r.state.approvals[0].id,true);assert.equal(r.total('a'),0);assert.throws(()=>r.useGoal(gid))});
test('saving needs approval and rejected operation leaves ledger unchanged',()=>{const r=setup();r.parent=true;r.addIncome('a',100,'saving','gift','Gift');r.parent=false;r.transferBetweenBuckets('a','saving','spending',50);assert.equal(r.wallet(r.state,'a').saving,100);r.parent=true;r.approveWallet(r.state.approvals[0].id,false);assert.equal(r.total('a'),100)});
test('parent operations require authentication and PIN is hashed',async()=>{const r=setup();assert.throws(()=>r.adjustPoints('a',20,'test'));await authenticate(r,'1234');assert.ok(r.state.settings.auth.hash);assert.ok(!JSON.stringify(r.state.settings.auth).includes('1234'));r.parent=false;await assert.rejects(authenticate(r,'5678'));await authenticate(r,'1234');assert.equal(r.parent,true)});
test('XP never deducted by penalty and no timed growth feature',()=>{const r=setup();r.complete('a',r.state.missions[0].id);r.parent=true;r.adjustPoints('a',-5,'Pengurang');assert.equal(r.state.children[0].xp,10);const src=require('node:fs').readFileSync('public/v2/domain.js','utf8');assert.ok(!/interestRate|compoundInterest|accrueInterest/.test(src))});
test('failed persistence cannot mutate saved state',()=>{const r=setup();r.adapter.write=()=>{throw Error('quota')};assert.throws(()=>r.complete('a',r.state.missions[0].id));assert.equal(r.state.children[0].points,2000)});

test('backup rejects invalid ledger and reward numbers',()=>{const {validate}=require('../public/v2/domain');const r=setup();const bad=structuredClone(r.state);bad.walletTransactions.push({id:'bad',childId:'a',bucket:'spending',amount:-1,status:'posted'});assert.throws(()=>validate(bad));bad.walletTransactions=[];bad.rewards[0].weight=-1;assert.throws(()=>validate(bad))});
test('missing target rolls back both transfer legs',()=>{const r=setup();r.parent=true;r.addIncome('a',100,'spending','gift','gift');assert.throws(()=>r.transferBetweenBuckets('a','spending','goal',50,'missing'));assert.equal(r.wallet(r.state,'a').spending,100);assert.equal(r.wallet(r.state,'a').goal,0)});

test('cancelled goal returns funds to saving with ledger entries',()=>{const r=setup();r.parent=true;r.save('goals',{childId:'a',name:'Bike',targetAmount:200});r.addIncome('a',100,'spending','gift','gift');const g=r.state.goals[0];r.transferBetweenBuckets('a','spending','goal',50,g.id);r.cancelGoal(g.id);assert.equal(r.wallet(r.state,'a').saving,50);assert.equal(r.total('a'),100);assert.equal(r.state.goals[0].status,'cancelled')});
test('reset day preserves XP and traces point reversal',()=>{const r=setup();r.complete('a',r.state.missions[0].id);r.parent=true;r.resetDay('a','Koreksi');assert.equal(r.state.children[0].xp,10);assert.equal(r.state.children[0].points,2000)});

test('mission completion uses active business date separately from createdAt',()=>{const r=setup();r.complete('a',r.state.missions[0].id,'2026-09-12');const c=r.state.completions.at(-1);assert.equal(c.completedDate,'2026-09-12');assert.equal(c.period,'2026-09-12');assert.notEqual(c.createdAt.slice(0,10),'2026-09-12')});
test('penalty preset records negative point transaction on active date',()=>{const r=setup();r.parent=true;r.addPenalty('a','Lupa tugas',5,'2026-09-12','pen-lupa');const t=r.state.pointTransactions.at(-1);assert.equal(t.amount,-5);assert.equal(t.businessDate,'2026-09-12');assert.equal(t.referenceId,'pen-lupa')});
test('reset date only cancels completions on that active date',()=>{const r=setup();r.complete('a',r.state.missions[0].id,'2026-09-12');r.complete('a',r.state.missions[0].id,'2026-09-13');r.parent=true;r.resetDay('a','Koreksi','2026-09-12');assert.equal(r.state.completions.find(c=>c.completedDate==='2026-09-12').status,'rejected');assert.equal(r.state.completions.find(c=>c.completedDate==='2026-09-13').status,'approved')});
test('gacha stores business date, time and pending decision',()=>{const r=setup();const result=r.performGacha('a','dated-key','2026-09-12');assert.equal(result.date,'2026-09-12');assert.ok(result.time);assert.equal(result.decision,'Belum Dipilih');assert.equal(result.childId,'a')});
